"""empty message

Revision ID: 624599b5d39b
Revises: cea2fdeacad5
Create Date: 2026-02-23 19:34:40.186321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624599b5d39b'
down_revision: Union[str, Sequence[str], None] = 'cea2fdeacad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'is_verified')
    op.drop_column('channel', 'type')
    op.drop_column('channel', 'language')
    op.drop_column('channel', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('channel', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('channel', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('channel', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
